set -g default-terminal "xterm-256color"
set -g default-shell "${SHELL}"
set -sg escape-time 0

set -g focus-events on

set -g status-style bg=black,fg=#a3bef5
set -g pane-border-style fg=#5b6a8a
set -g pane-active-border-style fg=#a3bef5
